fieldLayouts:
  087fe7b7-fbd5-4be3-871f-a77bb6d14ee8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c4ca65e2-d914-4e7a-b510-d296fd64ae9f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f40ddf5-d99a-4ea5-958d-61ecc44ea895 # Drink style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7845bca-9dab-44ff-987b-bb5563407371
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8753086a-029b-4530-87be-a3f3fab4e31e # Recipe Contents
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24d0b3e6-a6ce-48bb-aeed-0a88e812e94c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5399a1e2-6a54-4f3f-8826-8cc052b99f99
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 6a501b53-024d-4374-8fc7-cecb0eb5ba45 # Recipes
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
