columnSuffix: fvcovwkq
contentColumnType: text
fieldGroup: 053894d7-d999-48b9-849c-da5f5082b5f2 # Common
handle: Excerpt
instructions: null
name: Excerpt
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
