columnSuffix: null
contentColumnType: string
fieldGroup: ed6c6878-3c4a-41ff-9de0-5397f9496474 # Recipes
handle: recipeContents
instructions: null
name: 'Recipe Contents'
searchable: false
settings:
  contentTable: '{{%matrixcontent_recipecontents}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
