defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  556471e6-b6e4-4b51-af2c-39d53cd9e6da: # craftycoffee
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
