defaultPlacement: end
enableVersioning: true
handle: recipes
name: Recipes
propagationMethod: all
siteSettings:
  556471e6-b6e4-4b51-af2c-39d53cd9e6da: # craftycoffee
    enabledByDefault: true
    hasUrls: true
    template: recipes/_entry
    uriFormat: 'recipes/{slug}'
type: channel
